apiVersion: v1
kind: Service
metadata:
  labels:
    # should match with labels of deployment and pods
    app: spindb-idm
  name: spindb-svc # .namespace.svc.cluster.local
spec:
  selector:
    # should match with labels of deployment and pods
    app: spindb-idm
  ports:
    - name: client-port
      port: 2379
      protocol: TCP
      targetPort: 2379
    - name: peer-port
      port: 2380
      targetPort: 2380
    - name: pg-port
      port: 5432
      targetPort: 5432
  type: ClusterIP
  clusterIP: 10.98.98.157
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spindb-idm # postgres-0.postgres-db.namespace.svc.cluster.local
spec:
  selector:
    matchLabels:
      app: spindb-idm
  serviceName: spindb-svc # should match .metadata.name of headless service
  replicas: 3
  template:
    metadata:
      labels:
        app: spindb-idm
    spec:
      containers:
      - name: spindb-idm-pod
        imagePullPolicy: Always
        image: iliadmitriev/spin-db
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        ports:
        - containerPort: 5432
          name: pg-port
        - containerPort: 2379
          name: client-port
        - containerPort: 2380
          name: peer-port
        volumeMounts:
        - name: spindb-idm-data-pvc
          mountPath: /data
        env:
          - name: DATA_DIR
            value: /date/etcd.data
          - name: CLIENT_REQUEST_HOST
            value: 10.98.98.157
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: PATRONI_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: PATRONI_ETCD_HOST
            value: "$(CLIENT_REQUEST_HOST):2379"
          - name: PATRONI_POSTGRESQL_CONNECT_ADDRESS
            value: "$(POD_IP):5432"
  volumeClaimTemplates:
  - metadata:
      name: spindb-idm-data-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
